create table if not exists users (
    id bigint generated by default as identity primary key,
    username varchar(32) not null,
    email varchar(120) not null,
    password varchar(255) not null,
    email_verified boolean not null default false,
    email_verified_at timestamptz,
    total_kills integer not null default 0,
    total_assists integer not null default 0,
    total_deaths integer not null default 0,
    wallet integer not null default 0,
    xp integer not null default 0,
    outfit_id varchar(255),
    weapon_id varchar(255),
    weapon_skin_id varchar(255),
    grenade_skin_id varchar(255),
    mission_stats_json varchar(8000),
    admin boolean not null default false,
    version bigint not null default 0
);

create unique index if not exists uk_users_username on users (username);

create table if not exists email_verification_tokens (
    id bigint generated by default as identity primary key,
    token varchar(96) not null,
    user_id bigint not null,
    expires_at timestamptz not null,
    used_at timestamptz
);
create unique index if not exists uk_email_verification_token on email_verification_tokens (token);

create table if not exists lobby_rooms (
    id varchar(16) primary key,
    name varchar(255) not null,
    map_id varchar(32) not null,
    game_mode varchar(32),
    score_limit integer not null default 30,
    time_limit_minutes integer not null default 20,
    players integer not null default 0,
    max_players integer not null default 6,
    blue_players integer not null default 0,
    red_players integer not null default 0,
    allow_bots boolean not null default true,
    permanent boolean not null default false,
    last_activity_at timestamptz,
    version bigint not null default 0
);

create table if not exists friend_requests (
    id bigint generated by default as identity primary key,
    sender_id bigint not null,
    recipient_id bigint not null,
    status varchar(16) not null,
    created_at timestamptz not null
);
create unique index if not exists uk_friend_request_sender_recipient
    on friend_requests (sender_id, recipient_id);
create index if not exists ix_friend_requests_recipient_status
    on friend_requests (recipient_id, status);

create table if not exists friendships (
    id bigint generated by default as identity primary key,
    first_user_id bigint not null,
    second_user_id bigint not null,
    created_at timestamptz not null
);
create unique index if not exists uk_friendship_users on friendships (first_user_id, second_user_id);
create index if not exists ix_friendships_second_user on friendships (second_user_id);

create table if not exists room_invitations (
    id bigint generated by default as identity primary key,
    sender_id bigint not null,
    recipient_id bigint not null,
    room_code varchar(16) not null,
    status varchar(16) not null,
    created_at timestamptz not null,
    expires_at timestamptz not null default (current_timestamp + interval '30 minutes')
);
create index if not exists ix_room_invitations_recipient_status
    on room_invitations (recipient_id, status);

create table if not exists user_owned_outfits (
    user_id bigint not null,
    sort_order integer not null,
    outfit_id varchar(64) not null,
    primary key (user_id, sort_order)
);
create table if not exists user_owned_weapon_skins (
    user_id bigint not null,
    sort_order integer not null,
    skin_id varchar(64) not null,
    primary key (user_id, sort_order)
);
create table if not exists user_owned_grenade_skins (
    user_id bigint not null,
    sort_order integer not null,
    skin_id varchar(64) not null,
    primary key (user_id, sort_order)
);
create table if not exists user_owned_accessories (
    user_id bigint not null,
    sort_order integer not null,
    accessory_id varchar(64) not null,
    primary key (user_id, sort_order)
);
create table if not exists user_equipped_accessories (
    user_id bigint not null,
    sort_order integer not null,
    accessory_id varchar(64) not null,
    primary key (user_id, sort_order)
);
create table if not exists user_weapon_upgrades (
    user_id bigint not null,
    weapon_id varchar(64) not null,
    upgrade_level integer not null,
    primary key (user_id, weapon_id)
);
create table if not exists user_claimed_missions (
    user_id bigint not null,
    sort_order integer not null,
    mission_id varchar(64) not null,
    primary key (user_id, sort_order)
);
create table if not exists user_map_plays (
    user_id bigint not null,
    map_id varchar(64) not null,
    plays integer not null,
    primary key (user_id, map_id)
);
create table if not exists user_weapon_kills (
    user_id bigint not null,
    weapon_id varchar(64) not null,
    kills integer not null,
    primary key (user_id, weapon_id)
);

alter table users add column if not exists version bigint not null default 0;
alter table lobby_rooms add column if not exists version bigint not null default 0;
alter table room_invitations add column if not exists expires_at timestamptz;
update room_invitations
set expires_at = created_at + interval '30 minutes'
where expires_at is null;
alter table room_invitations alter column expires_at set not null;

delete from email_verification_tokens where user_id not in (select id from users);
delete from friend_requests
where sender_id not in (select id from users) or recipient_id not in (select id from users);
delete from friendships
where first_user_id not in (select id from users) or second_user_id not in (select id from users);
delete from room_invitations
where sender_id not in (select id from users)
   or recipient_id not in (select id from users)
   or room_code not in (select id from lobby_rooms);

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'fk_email_token_user') then
        alter table email_verification_tokens
            add constraint fk_email_token_user foreign key (user_id) references users(id) on delete cascade;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'fk_friend_request_sender') then
        alter table friend_requests
            add constraint fk_friend_request_sender foreign key (sender_id) references users(id) on delete cascade;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'fk_friend_request_recipient') then
        alter table friend_requests
            add constraint fk_friend_request_recipient foreign key (recipient_id) references users(id) on delete cascade;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'fk_friendship_first_user') then
        alter table friendships
            add constraint fk_friendship_first_user foreign key (first_user_id) references users(id) on delete cascade;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'fk_friendship_second_user') then
        alter table friendships
            add constraint fk_friendship_second_user foreign key (second_user_id) references users(id) on delete cascade;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'fk_room_invitation_sender') then
        alter table room_invitations
            add constraint fk_room_invitation_sender foreign key (sender_id) references users(id) on delete cascade;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'fk_room_invitation_recipient') then
        alter table room_invitations
            add constraint fk_room_invitation_recipient foreign key (recipient_id) references users(id) on delete cascade;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'fk_room_invitation_room') then
        alter table room_invitations
            add constraint fk_room_invitation_room foreign key (room_code) references lobby_rooms(id) on delete cascade;
    end if;
end $$;

do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'user_owned_outfits',
        'user_owned_weapon_skins',
        'user_owned_grenade_skins',
        'user_owned_accessories',
        'user_equipped_accessories',
        'user_weapon_upgrades',
        'user_claimed_missions',
        'user_map_plays',
        'user_weapon_kills'
    ]
    loop
        if not exists (
            select 1 from pg_constraint
            where conname = 'fk_' || table_name || '_user'
        ) then
            execute format(
                'alter table %I add constraint %I foreign key (user_id) references users(id) on delete cascade',
                table_name,
                'fk_' || table_name || '_user'
            );
        end if;
    end loop;
end $$;
