[build]
  base = "deadzone-client"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_ORIGIN = "https://deadzone-fvcb.onrender.com"
  VITE_SUPABASE_URL = "https://hrkyzclzsjvbuxfzytxr.supabase.co"
  VITE_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_e1tzjPkYjaO8zIqNV1jIFQ_Ffq_pLXp"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
