[build]
  base = "deadzone-client"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_ORIGIN = "https://deadzone-fvcb.onrender.com"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
