/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/apocalyptic_city.glb --transform --shadows --name ApocalypticCityModel --output src/components/maps/ApocalypticCityModel.jsx 
...
*/

import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier' // ייבוא הפיזיקה

const APOCALYPTIC_CITY_URL = '/model/apocalyptic_city-transformed.glb'
const DRACO_DECODER_PATH = '/draco/'

useGLTF.setDecoderPath(DRACO_DECODER_PATH)

export function Model(props) {
    const { nodes, materials } = useGLTF(APOCALYPTIC_CITY_URL, DRACO_DECODER_PATH)

    return (
        // type="fixed" מונע מהעיר ליפול או לזוז כשהשחקנים מתנגשים בה
        // colliders="trimesh" יוצר פיזיקה מדויקת לפי המבנה של המבנים והכבישים
        <RigidBody type="fixed" colliders="trimesh">
            <group {...props} dispose={null}>
                <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials['02___Default']} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials['02___Defaultff']} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials['02___Defaultffff']} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials['02___Defaultffffff']} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials['15___Defaultddd']} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials['16___Default']} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials['19___Defaultdffee']} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials['19___Defaultdffeegg']} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials['19___Defaultdffeegggg']} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials.Material__1276} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials.Material__1277} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_14.geometry} material={materials['01___Defaultgggggggg']} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_15.geometry} material={materials['01___Defaultyyyy']} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_16.geometry} material={materials['13___Default']} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_17.geometry} material={materials['14___Default']} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_18.geometry} material={materials['19___Default']} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_19.geometry} material={materials['19___Defaultd']} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_20.geometry} material={materials['19___Defaultdff']} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_21.geometry} material={materials['19___Defaultdffeedd']} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_23.geometry} material={materials['19___Defaultdffeeggff']} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_25.geometry} material={materials.vray_22___Defaultfff} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_26.geometry} material={materials.wire_225088199} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_28.geometry} material={materials.wire_228184153} rotation={[-Math.PI / 2, 0, 0]} />
            </group>
        </RigidBody>
    )
}

useGLTF.preload(APOCALYPTIC_CITY_URL, DRACO_DECODER_PATH)